spring:
  application:
    name: Bookstore
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    throw-exception-if-no-handler-found=true:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibrenate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      springframework:
        security:
          web:
            authentication=ERROR:

  logging:
    level:
      org:
        springdoc=DEBUG:

        springframework:
          web=DEBUG:

jwt:
  secret: ${JWT_SECRET}